backend:
  name: git-gateway
  branch: master
media_folder: "imgs/uploads"
collections: 
  - name: "Content"
    label: "Site Content"
    files:
      - label: "About Info"
        name: "about"
        file: "_posts/about/about.json"
        format: "json"
        description: "The paragraphs in the 'About Me' section of the site"
        create: true
        fields:
          - label: "About paragraphs"
            name: "about-paragraphs"
            widget: "list"
            fields:
              - {label: "P Number", name: "p-number", widget: "string"}
              - {label: "P Text", name: "p-text", widget: "text"}
      