backend:
  name: git-gateway
  branch: master
media_folder: "imgs/uploads"
collections: 
  - name: "Content"
    label: "Site Content"
    files:
      - label: "About Info"
        name: "about"
        file: "_posts/about/about.json"
        format: "json"
        description: "The paragraphs in the 'About Me' section of the site"
        create: true
        fields:
          - label: "About paragraphs"
            name: "aboutParagraphs"
            widget: "list"
            fields:
              - {label: "P Number", name: "p-number", widget: "string"}
              - {label: "P Text", name: "p-text", widget: "text"}
      - label: "Resume"
        name: "resume"
        file: "_posts/resume/resume.json"
        format: "json"
        create: true
        fields:
          - label: "Coding Stuff"
            name: "codingStuff"
            widget: "list"
            fields:
              - {
                label: "List Item Content",
                name: "liContent",
                widget: "string"
              }
              - {
                label: "Is it a parent?",
                name: "isParent",
                widget: "boolean",
                default: false
              }
              - {
                label: "Is it a child?",
                name: "isChild",
                widget: "boolean",
                default: false
              }
              - {
                label: "Parent List Item",
                name: "parentLi",
                widget: "string",
                default: NULL,
                required: false
              }
          - label: "Professional Specialties"
            name: "proSpecs"
            widget: "list"
            fields:
              - {
                label: "List Item Content",
                name: "liContent",
                widget: "string"
              }
              - {
                label: "Is it a parent?",
                name: "isParent",
                widget: "boolean",
                default: false
              }
              - {
                label: "Is it a child?",
                name: "isChild",
                widget: "boolean",
                default: false
              }
              - {
                label: "Parent List Item",
                name: "parentLi",
                widget: "string",
                default: NULL,
                required: false
              }
          - label: "Education"
            name: "education"
            widget: "list"
            fields:
              - {
                label: "List Item Content",
                name: "liContent",
                widget: "string"
              }
              - {
                label: "Is it a parent?",
                name: "isParent",
                widget: "boolean",
                default: false
              }
              - {
                label: "Is it a child?",
                name: "isChild",
                widget: "boolean",
                default: false
              }
              - {
                label: "Parent List Item",
                name: "parentLi",
                widget: "string",
                default: NULL,
                required: false
              }
      